# Generated by Django 5.0.3 on 2024-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('publication_date', models.DateField()),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
